/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  IKApmNftVoucherSale,
  IKApmNftVoucherSaleInterface,
} from "../IKApmNftVoucherSale";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "apmCoinAddress",
        type: "address",
      },
    ],
    name: "SetApmCoin",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "apmCoinAddress",
        type: "address",
      },
    ],
    name: "SetNftVoucher",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "feeTo",
        type: "address",
      },
    ],
    name: "SetFeeTo",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "SetTokenId",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "apmPerNft",
        type: "uint256",
      },
    ],
    name: "SetApmPerNft",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "step",
        type: "uint256",
      },
    ],
    name: "SetStep",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "step",
        type: "uint256",
      },
    ],
    name: "SetSaleLimit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "saleCount",
        type: "uint256",
      },
    ],
    name: "SetSaleCount",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "saleName",
        type: "string",
      },
    ],
    name: "SetSaleName",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        name: "saleDescription",
        type: "string",
      },
    ],
    name: "SetSaleDescription",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603580601d6000396000f3fe6080604052600080fdfea165627a7a72305820f1e275c2c6494186c775cb94b192e90393447b5f9b1676363a40af4b309e57ca0029";

type IKApmNftVoucherSaleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: IKApmNftVoucherSaleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class IKApmNftVoucherSale__factory extends ContractFactory {
  constructor(...args: IKApmNftVoucherSaleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<IKApmNftVoucherSale> {
    return super.deploy(overrides || {}) as Promise<IKApmNftVoucherSale>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): IKApmNftVoucherSale {
    return super.attach(address) as IKApmNftVoucherSale;
  }
  connect(signer: Signer): IKApmNftVoucherSale__factory {
    return super.connect(signer) as IKApmNftVoucherSale__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IKApmNftVoucherSaleInterface {
    return new utils.Interface(_abi) as IKApmNftVoucherSaleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKApmNftVoucherSale {
    return new Contract(address, _abi, signerOrProvider) as IKApmNftVoucherSale;
  }
}
