/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IKApmNftVoucherSaleInterface extends utils.Interface {
  functions: {};

  events: {
    "SetApmKrwPrice(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetApmKrwPrice"): EventFragment;
}

export type SetApmKrwPriceEvent = TypedEvent<
  [string, BigNumber],
  { account: string; price: BigNumber }
>;

export type SetApmKrwPriceEventFilter = TypedEventFilter<SetApmKrwPriceEvent>;

export interface IKApmNftVoucherSale extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IKApmNftVoucherSaleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "SetApmKrwPrice(address,uint256)"(
      account?: string | null,
      price?: null
    ): SetApmKrwPriceEventFilter;
    SetApmKrwPrice(
      account?: string | null,
      price?: null
    ): SetApmKrwPriceEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
