/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface StaffRoleInterface extends utils.Interface {
  functions: {
    "renounceStaff()": FunctionFragment;
    "addStaff(address)": FunctionFragment;
    "isStaff(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "renounceStaff",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addStaff", values: [string]): string;
  encodeFunctionData(functionFragment: "isStaff", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "renounceStaff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addStaff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isStaff", data: BytesLike): Result;

  events: {
    "StaffAdded(address)": EventFragment;
    "StaffRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "StaffAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StaffRemoved"): EventFragment;
}

export type StaffAddedEvent = TypedEvent<[string], { account: string }>;

export type StaffAddedEventFilter = TypedEventFilter<StaffAddedEvent>;

export type StaffRemovedEvent = TypedEvent<[string], { account: string }>;

export type StaffRemovedEventFilter = TypedEventFilter<StaffRemovedEvent>;

export interface StaffRole extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StaffRoleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    renounceStaff(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addStaff(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isStaff(account: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  renounceStaff(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addStaff(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isStaff(account: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    renounceStaff(overrides?: CallOverrides): Promise<void>;

    addStaff(account: string, overrides?: CallOverrides): Promise<void>;

    isStaff(account: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "StaffAdded(address)"(account?: string | null): StaffAddedEventFilter;
    StaffAdded(account?: string | null): StaffAddedEventFilter;

    "StaffRemoved(address)"(account?: string | null): StaffRemovedEventFilter;
    StaffRemoved(account?: string | null): StaffRemovedEventFilter;
  };

  estimateGas: {
    renounceStaff(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addStaff(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isStaff(account: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    renounceStaff(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addStaff(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isStaff(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
